### ISSUE TITLE
python example doesn't work

### ISSUE THREAD

**Issue by xamount** [kortina/run-in-terminal#11]
${relativeFile} seems to run the absolute path of the file prefixed with a . - which fails of course
so /home/JoeSmith/main.py gets executed as 
`python ./home/JoeSmith/main.py` 

I was able to get it work by using  ${file} instead after reading about the relevant tokens in send-to-terminal's documentation.

**Comment by kortina** [comment]
Oh, interesting. Are you on windows? "./" is the current directory on Unix systems. Not sure this is worth changing as it seems you have figured out a work around.
