### ISSUE TITLE
Settings name same as Send to Terminal

### ISSUE THREAD

**Issue by TiagoCAAmorim** [kortina/run-in-terminal#9]
You mention this extension was inspired by the Send to Terminal extension. I'd suggest you to change the name of the setting **sendToTerminal.commands** to something like **runInTerminal.commands**. This way you'll avoid conflict in case you have both extensions installed. It is also usefull to have all settings and commands starting with the same name, so it is simpler to find these in the user settings search.

**Comment by kortina** [comment]
This is now resolved https://github.com/kortina/run-in-terminal/commit/59762b2d3a500c5e5b9e8c4cd222787cfa239d7b
